name: Release
run-name: ${{ github.actor }} is playing with Github releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input version number'
        required: true
        default: '0.0.0-dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - uses: actions/checkout@v2

      - name: Build Windows App
        run: GOOS=linux GOARCH=amd64 go build -ldflags="-X main.version=${{ github.event.inputs.version }}" -o hello_world_linux_amd64 && ./hello_world_linux_amd64
