name: Release the Ezra
run-name: ${{ github.actor }} is playing with Github releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input version number'
        required: true
        default: '0.0.0-dev'

jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "Env: ${{ github.event.inputs.version }}" 
