name: Release
run-name: ${{ github.actor }} is playing with Github releases
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Input version number'
        required: true
        default: '0.0.0-dev'

jobs:
  build:
    steps:
      - name: Install go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20
      - uses: actions/checkout@v2

      - name: Build Windows App
        run: GOOS=windows GOARCH=amd64 go build -o hello_world_windows_amd64.exe
